---
- name: Install Firewall Packages
  apt:
    name: "{{ _firewall_packages }}"
    state: latest

- name: "Configure firewall defaults"
  ufw: 
    direction: "{{ item.direction }}" 
    policy: "{{ item.policy }}"
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart firewall on Debian

- name: "Configure ufw rules"
  ufw: 
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ boc_firewall_ufw_rules }}"
  when: boc_firewall_ufw_rules is defined and (boc_firewall_ufw_rules | length > 0)
  notify:
    - restart firewall on Debian

- name: "Configure ufw src"
  ufw: 
    rule: "{{ item.rule }}"
    src: "{{ item.src }}"
  with_items: "{{ boc_firewall_ufw_src }}"
  when: boc_firewall_ufw_src is defined and (boc_firewall_ufw_src | length > 0)
  notify:
    - restart firewall on Debian

- name: "Enable ufw logging"
  ufw: 
    logging: "{{ boc_firewall_ufw_logging }}"
  notify:
    - restart firewall on Debian

- name: "Enable ufw"
  ufw: 
    state: enabled

