---
# handlers file for bitofcode.linux_common
- name: restart sshd on RedHat
  service:
    name: "{{ _boc_redhat_sshd_service_name }}"
    state: restarted

- name: restart sshd on Debian
  service:
    name: "{{ _boc_debian_sshd_service_name }}"
    state: restarted

- name: restart firewall on RedHat
  service:
    name: "{{ _boc_redhat_firewall_service_name }}"
    state: restarted

- name: restart firewall on Debian
  service:
    name: "{{ _boc_debian_firewall_service_name }}"
    state: restarted
